[package]
name = "bufdither-rust"
version = "0.1.0"
authors = ["Yury Benesh <ybxsoft@tut.by>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
